### ISSUE TITLE
TO-DO general clean up. 

### ISSUE THREAD

**Issue by melontini** [melontini/public-plus-#1]
Currently, the pack is 40(!) megabytes without any mods. I believe this can be cut down.
Also, scripts themselves are terrible and need to be beautified. 
- [x] Somehow reduce pack's size. Update: it's impossible without removing the cool panorama
- [x] Clean up advancement scripts.
- [x] Clean up recipe scripts. 
- [x] Reorganize some stuff.
- [ ] Modifiers can be extracted from plus- tweaker, so I should probably do this.
